# Generated by Django 5.2.4 on 2025-09-05 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0003_purchase_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='buying_price',
        ),
        migrations.AddField(
            model_name='report',
            name='total_product_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
